# Generated by Django 5.2 on 2026-07-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_goodimage_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='goodimage',
            name='image',
            field=models.ImageField(default='', upload_to='goods/%Y/%m/'),
            preserve_default=False,
        ),
    ]
